config/routes.rb
Rails.application.routes.draw do
  resources :requests

  root 'index#index'
  mount Mobile::Engine, at: "/mobile"
end

app/models/data/seo.rb
module Seo
  TITLE = 'Курсы Ruby on Rails в Москве'
  DESCRIPTION = 'Оффлайн курсы Ruby on Rails в Москве – самый современный и востребованный язык программирования, обучение с молодыми профессионалами – выпускниками топовых вузов России и призёрами олимпиад'
  KEYWORDS = 'курсы ruby on rails москва ror обучение преподаватель руби оффлайн в москве онлайн язык программирования научиться программировать повышение квалификации'
end

app/models/option.rb
class Option < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :plan_options
  has_many :options, through: :plan_options
end

app/models/plan_option.rb
class PlanOption < ActiveRecord::Base
  belongs_to :plan
  belongs_to :option
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :plan
  after_save :send_emails

  private
    def send_emails
      RequestNotifier.new(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  require "browser"

  def index
    if browser.chrome?
      redirect_to '/mobile'
    end
    @plans = Plan.all.to_json(include: :options)
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { head :no_content }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.permit(:plan_id, :name, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def list_image_assets(dir_name)
    path = File.expand_path("../../../app/assets/images/#{dir_name}", __FILE__)
    full_paths = Dir.glob "#{path}/**.*"
    assets_map = {}
    full_paths.each do |p|
      original_name = File.basename p
      asset_path    = asset_path p[p.index("#{dir_name}")..-1]
      assets_map[original_name] = asset_path
    end
    assets_map.to_json
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/index/_courses.html.slim
div.content.menu-2#two
  .content-body
    svg#info-1
    = image_tag('icons/ruby.png', height: 355, class: 'ruby-icon')
    .row-1.center-text
      h1.text-danger
        | Курсы программирования с уклоном на 
        | монетизацию своих знаний
      / p.center-text Ruby on Rails является самым современным, востребованным, быстро развивающимся 
      / p.center-text и лёгким для обучения языком программирования
      p Наша цель – не просто научить вас программировать. Мы научим вас быстро воплощать
      p идеи в реальность и зарабатывать на своих знаниях в самой востребованной области 21 века
    .bubble.one
      .hi-icon-effect-1.hi-icon-effect-1a
        a.hi-icon.fa-line-chart
      span Самый современный и быстро развивающийся язык по версии <a href='http://codering.info/trending' target='_blank'>Codering</a>
    .bubble.two 
      .hi-icon-effect-1.hi-icon-effect-1a
        a.hi-icon.fa-rocket
      span Минимальное время от начала разработки до реального проекта
    .bubble.three 
      .hi-icon-effect-1.hi-icon-effect-1a
        a.hi-icon.fa-globe
      span Востребованность во всех странах мира
    .bubble.four.animated 
      .hi-icon-effect-1.hi-icon-effect-1a
        a.hi-icon.fa-female @mouseover='bubble(4)' @mouseleave='bubble(4, false)'
      span.hidden.animated :class="{'fadeInDown': bubbles[4]}" Девушкам нравятся программисты Ruby ;)
    .bubble.five.animated
      .hi-icon-effect-1.hi-icon-effect-1a
        a.hi-icon.fa-graduation-cap @mouseover='bubble(5)' @mouseleave='bubble(5, false)'
      span.hidden.animated :class="{'fadeInDown': bubbles[5]}" Легок в изучении, понятен и прост в освоении

app/views/index/_main.html.slim
div.content.menu-1#one
  .center-text-wrap
    .center-text
      h1 
        #line-1 Курсы программирования
        #line-2 Ruby On Rails
        #line-3 г. Москва
  #video_bg
    video#video(loop autoplay muted poster="#{ image_path('backgrounds/video-placeholder.png') }")
      source src="videos/ruby.webm" type="video/webm" 
      / source src="videos/ruby.mp4" type="video/mp4" 
  .scroll_down 
    .mouse
      .mouse-mouvement
    .mouse-message Прокрутите

app/views/index/_menu.html.slim
.tabs.tabs-style-underline
  nav
    ul
      li :class="{'tab-current': current_tab == 1}" @click='menu(1)'
        a href="#main" 
          span.icon.fa.fa-diamond.ruby-color
          span Главная
      li :class="{'tab-current': current_tab == 2}" @click='menu(2)'
        a href="#courses" 
          span.icon.fa.fa-code
          span Курсы
      li :class="{'tab-current': current_tab == 3}" @click='menu(3)'
        a href="#teachers" 
          span.icon.fa.fa-users
          span Преподаватели
      li :class="{'tab-current': current_tab == 4}" @click='menu(4)'
        a href="#prices" 
          span.icon.fa.fa-dollar
          span Цены
      li :class="{'tab-current': current_tab == 5}" @click='menu(5)'
        a href="#signup" 
          span.icon.fa.fa-send
          span Записаться

app/views/index/_overlay.html.slim
.overlay.overlay-scale :class="{
  'open': overlay,
  'plan-1': selected_plan.id == 1,
  'plan-2': selected_plan.id == 2,
  'plan-3': selected_plan.id == 3,
}"
  button.overlay-close type='button' @click='overlay = false' Close
  .valign-wrapper.full-size
    .valign style='width: 100%'
      .row style='padding: 30px'
        h1.center
          | {{ selected_plan.title | uppercase}}
        img :src='get_img(selected_plan)'
        .options-list
          div v-for='option in selected_plan.options'
            h3 
              i.fa.fa-plus
              | {{ option.title }}

app/views/index/_prices.html.slim
= render 'overlay'
div.content.menu-4#four
  / h1 Choose your destiny
  #triangle-topleft.animated
  #triangle-bottomright.animated
  #pricing-table
    .pricing-option v-for='plan in plans' :class="{'selected': selected_plan == plan}"
      .pricing-header 
        | {{ plan.title }}
      .pricing-info-wrapper
        div
          .price 
            | {{ plan.price | price }}
          .rubbles рублей/курс
        div
          img :src="get_img(plan)"
        div
          button :class="{'selected': selected_plan == plan}" @click='select_plan(plan)' 
            | {{selected_plan == plan ? 'Выбрано' : 'Выбрать'}}

app/views/index/_signup.html.slim
div.content.menu-5#five
  .before_signup v-show='!request_sent'
    h1 Записаться на курсы
    div
      span.input.input--hoshi
        input#input-4.input__field.input__field--hoshi type="text" v-model='request.name'
        label.input__label.input__label--hoshi
          span.input__label-content.input__label-content--hoshi Имя
    div
      span.input.input--hoshi
        input#request-phone.input__field.input__field--hoshi(type="text" v-model='request.phone' v-el:phone)
        label.input__label.input__label--hoshi
          span.input__label-content.input__label-content--hoshi Телефон
    div style='margin-top: 50px'
      button.btn.btn-4.btn-4c.icon-arrow-right @click='signup' Записаться
  .after_signup v-show='request_sent'
    .after_signup_wrapper
      h1 Заявка отправлена!
      h4 
        | {{ request.name }}, мы перезвоним Вам в ближайшее время
  .more-about-courses подробная информация о курсах

app/views/index/_teachers.html.slim
div.content.menu-3#three
  .content-body
    h1 Молодые преподаватели из ведущих вузов страны
    .tutor-list
      .tutor
        = image_tag 'teachers/kolyadin.png'
        h2 Максим Колядин
        h4
          i.fa.fa-university
          | НИУ ВШЭ
          
      .tutor
        = image_tag 'teachers/yanberdin.png'
        h2 Тимур Янбердин
        h4
          i.fa.fa-university
          | НИУ ВШЭ
      .tutor
        = image_tag 'teachers/teacher_3.jpg'
        h2 Альберт Корнеенко
        h4
          i.fa.fa-university
          | МГУ
    .tutor-info style='margin-top: 25px'
        .info-line.animated
          = image_tag('icons/atom.png')
          | Призеры олимпиад по программированию
        .info-line.animated 
          = image_tag('icons/globe.png')
          | Выпускники ведущих вузов страны
    .tutor-info
        .info-line.animated 
          = image_tag('icons/protective-gloves.png')
          | Профессионалы, получившие опыт в топовых <br> IT-компаниях, таких как Яндекс
        .info-line.animated 
          = image_tag('icons/rocket.png')
          | Основатели собственных компаний и монетизированных онлайн-сервисов
        

app/views/index/index.html.slim
= render 'menu'
= render 'main'
= render 'courses'
= render 'teachers'  
= render 'prices'
= render 'signup'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title = Seo::TITLE
    meta name='keywords' content="#{ Seo::KEYWORDS }"
    meta name='description' content="#{ Seo::DESCRIPTION }"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body plans="#{ @plans }" assets="#{ list_image_assets 'icons' }"
    #fakeLoader
    = yield

app/views/request_notifier/new.html.slim
h2 Новая заявка
p Имя: #{@request.name}
p Телефон: #{@request.phone}

app/views/request_notifier/new.text.erb
RequestNotifier#new

<%= @greeting %>, find me in app/views/request_notifier/new.text.erb

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plan_id %><br>
    <%= f.text_field :plan_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th>Plan</th>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.plan %></td>
        <td><%= request.name %></td>
        <td><%= request.phone %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plan:</strong>
  <%= @request.plan %>
</p>

<p>
  <strong>Name:</strong>
  <%= @request.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @request.phone %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>